@ECHO OFF
COPY "%~dp0A25\3FR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\3fr.ico" /Y
COPY "%~dp0A25\ARI.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\ari.ico" /Y
COPY "%~dp0A25\ARW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\arw.ico" /Y
COPY "%~dp0A25\AVIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\avif.ico" /Y
COPY "%~dp0A25\B64.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\b64.ico" /Y
COPY "%~dp0A25\BAY.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\bay.ico" /Y
COPY "%~dp0A25\BMP.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\bmp.ico" /Y
COPY "%~dp0A25\CAP.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cap.ico" /Y
COPY "%~dp0A25\CR2.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cr2.ico" /Y
COPY "%~dp0A25\CR3.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cr3.ico" /Y
COPY "%~dp0A25\CRW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\crw.ico" /Y
COPY "%~dp0A25\CUR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cur.ico" /Y
COPY "%~dp0A25\CUT.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cut.ico" /Y
COPY "%~dp0A25\DATA.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\data.ico" /Y
COPY "%~dp0A25\DCR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dcr.ico" /Y
COPY "%~dp0A25\DCS.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dcs.ico" /Y
COPY "%~dp0A25\DDS.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dds.ico" /Y
COPY "%~dp0A25\DIB.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dib.ico" /Y
COPY "%~dp0A25\DNG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dng.ico" /Y
COPY "%~dp0A25\DRF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\drf.ico" /Y
COPY "%~dp0A25\EIP.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\eip.ico" /Y
COPY "%~dp0A25\EMF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\emf.ico" /Y
COPY "%~dp0A25\ERF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\erf.ico" /Y
COPY "%~dp0A25\EXIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\exif.ico" /Y
COPY "%~dp0A25\EXR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\exr.ico" /Y
COPY "%~dp0A25\FFF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\fff.ico" /Y
COPY "%~dp0A25\GIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\gif.ico" /Y
COPY "%~dp0A25\GPR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\gpr.ico" /Y
COPY "%~dp0A25\HDR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\hdr.ico" /Y
COPY "%~dp0A25\HEIC.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\heic.ico" /Y
COPY "%~dp0A25\HEIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\heif.ico" /Y
COPY "%~dp0A25\ICO.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\ico.ico" /Y
COPY "%~dp0A25\IIQ.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\iiq.ico" /Y
COPY "%~dp0A25\JFIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jfif.ico" /Y
COPY "%~dp0A25\JPE.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jpe.ico" /Y
COPY "%~dp0A25\JPEG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jpeg.ico" /Y
COPY "%~dp0A25\JPG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jpg.ico" /Y
COPY "%~dp0A25\JXL.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jxl.ico" /Y
COPY "%~dp0A25\K25.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\k25.ico" /Y
COPY "%~dp0A25\KDC.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\kdc.ico" /Y
COPY "%~dp0A25\MDC.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\mdc.ico" /Y
COPY "%~dp0A25\MEF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\mef.ico" /Y
COPY "%~dp0A25\MOS.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\mos.ico" /Y
COPY "%~dp0A25\MRW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\mrw.ico" /Y
COPY "%~dp0A25\NEF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\nef.ico" /Y
COPY "%~dp0A25\NRW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\nrw.ico" /Y
COPY "%~dp0A25\OBM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\obm.ico" /Y
COPY "%~dp0A25\ORF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\orf.ico" /Y
COPY "%~dp0A25\PBM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pbm.ico" /Y
COPY "%~dp0A25\PCX.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pcx.ico" /Y
COPY "%~dp0A25\PEF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pef.ico" /Y
COPY "%~dp0A25\PGM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pgm.ico" /Y
COPY "%~dp0A25\PNG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\png.ico" /Y
COPY "%~dp0A25\PPM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\ppm.ico" /Y
COPY "%~dp0A25\PSD.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\psd.ico" /Y
COPY "%~dp0A25\PTX.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\ptx.ico" /Y
COPY "%~dp0A25\PXN.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pxn.ico" /Y
COPY "%~dp0A25\QOI.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\qoi.ico" /Y
COPY "%~dp0A25\R3D.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\r3d.ico" /Y
COPY "%~dp0A25\RAF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\raf.ico" /Y
COPY "%~dp0A25\RAW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\raw.ico" /Y
COPY "%~dp0A25\RW2.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\rw2.ico" /Y
COPY "%~dp0A25\RWL.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\rwl.ico" /Y
COPY "%~dp0A25\RWZ.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\rwz.ico" /Y
COPY "%~dp0A25\SR2.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\sr2.ico" /Y
COPY "%~dp0A25\SRF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\srf.ico" /Y
COPY "%~dp0A25\SRW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\srw.ico" /Y
COPY "%~dp0A25\SVG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\svg.ico" /Y
COPY "%~dp0A25\TGA.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\tga.ico" /Y
COPY "%~dp0A25\TIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\tif.ico" /Y
COPY "%~dp0A25\TIFF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\tiff.ico" /Y
COPY "%~dp0A25\WEBP.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\webp.ico" /Y
COPY "%~dp0A25\WIC.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\wic.ico" /Y
COPY "%~dp0A25\WMF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\wmf.ico" /Y
COPY "%~dp0A25\WPG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\wpg.ico" /Y
COPY "%~dp0A25\X3F.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\x3f.ico" /Y
COPY "%~dp0A25\XBM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\xbm.ico" /Y
COPY "%~dp0A25\XPM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\xpm.ico" /Y
