@ECHO OFF
COPY "%~dp0A25\3fr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.3fr.ico" /Y
COPY "%~dp0A25\3g2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.3g2.ico" /Y
COPY "%~dp0A25\3gp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.3gp.ico" /Y
COPY "%~dp0A25\7z.ico" "%ProgramFiles%\PhotoQt\filetypes\image.7z.ico" /Y
COPY "%~dp0A25\aai.ico" "%ProgramFiles%\PhotoQt\filetypes\image.aai.ico" /Y
COPY "%~dp0A25\afm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.afm.ico" /Y
COPY "%~dp0A25\ai.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ai.ico" /Y
COPY "%~dp0A25\alb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.alb.ico" /Y
COPY "%~dp0A25\alias.ico" "%ProgramFiles%\PhotoQt\filetypes\image.alias.ico" /Y
COPY "%~dp0A25\als.ico" "%ProgramFiles%\PhotoQt\filetypes\image.als.ico" /Y
COPY "%~dp0A25\amv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.amv.ico" /Y
COPY "%~dp0A25\ani.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ani.ico" /Y
COPY "%~dp0A25\apm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.apm.ico" /Y
COPY "%~dp0A25\apng.ico" "%ProgramFiles%\PhotoQt\filetypes\image.apng.ico" /Y
COPY "%~dp0A25\ari.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ari.ico" /Y
COPY "%~dp0A25\arq.ico" "%ProgramFiles%\PhotoQt\filetypes\image.arq.ico" /Y
COPY "%~dp0A25\art.ico" "%ProgramFiles%\PhotoQt\filetypes\image.art.ico" /Y
COPY "%~dp0A25\arw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.arw.ico" /Y
COPY "%~dp0A25\asf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.asf.ico" /Y
COPY "%~dp0A25\avi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.avi.ico" /Y
COPY "%~dp0A25\avif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.avif.ico" /Y
COPY "%~dp0A25\avifs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.avifs.ico" /Y
COPY "%~dp0A25\avs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.avs.ico" /Y
COPY "%~dp0A25\bay.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bay.ico" /Y
COPY "%~dp0A25\bie.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bie.ico" /Y
COPY "%~dp0A25\bm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bm.ico" /Y
COPY "%~dp0A25\bmp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bmp.ico" /Y
COPY "%~dp0A25\bmq.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bmq.ico" /Y
COPY "%~dp0A25\bpg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bpg.ico" /Y
COPY "%~dp0A25\bw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bw.ico" /Y
COPY "%~dp0A25\c4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.c4.ico" /Y
COPY "%~dp0A25\cal.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cal.ico" /Y
COPY "%~dp0A25\cals.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cals.ico" /Y
COPY "%~dp0A25\cap.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cap.ico" /Y
COPY "%~dp0A25\cb7.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cb7.ico" /Y
COPY "%~dp0A25\cbr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cbr.ico" /Y
COPY "%~dp0A25\cbt.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cbt.ico" /Y
COPY "%~dp0A25\cbz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cbz.ico" /Y
COPY "%~dp0A25\cg3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cg3.ico" /Y
COPY "%~dp0A25\cg4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cg4.ico" /Y
COPY "%~dp0A25\ch.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ch.ico" /Y
COPY "%~dp0A25\cine.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cine.ico" /Y
COPY "%~dp0A25\cr2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cr2.ico" /Y
COPY "%~dp0A25\cr3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cr3.ico" /Y
COPY "%~dp0A25\crr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.crr.ico" /Y
COPY "%~dp0A25\crw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.crw.ico" /Y
COPY "%~dp0A25\cs1.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cs1.ico" /Y
COPY "%~dp0A25\ct.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct.ico" /Y
COPY "%~dp0A25\ct1.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct1.ico" /Y
COPY "%~dp0A25\ct2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct2.ico" /Y
COPY "%~dp0A25\ct3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct3.ico" /Y
COPY "%~dp0A25\ct4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct4.ico" /Y
COPY "%~dp0A25\cube.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cube.ico" /Y
COPY "%~dp0A25\cur.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cur.ico" /Y
COPY "%~dp0A25\cut.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cut.ico" /Y
COPY "%~dp0A25\dc2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dc2.ico" /Y
COPY "%~dp0A25\dcm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dcm.ico" /Y
COPY "%~dp0A25\dcr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dcr.ico" /Y
COPY "%~dp0A25\dcs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dcs.ico" /Y
COPY "%~dp0A25\dcx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dcx.ico" /Y
COPY "%~dp0A25\dds.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dds.ico" /Y
COPY "%~dp0A25\dfont.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dfont.ico" /Y
COPY "%~dp0A25\dib.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dib.ico" /Y
COPY "%~dp0A25\dic.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dic.ico" /Y
COPY "%~dp0A25\djv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.djv.ico" /Y
COPY "%~dp0A25\djvu.ico" "%ProgramFiles%\PhotoQt\filetypes\image.djvu.ico" /Y
COPY "%~dp0A25\dng.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dng.ico" /Y
COPY "%~dp0A25\dpx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dpx.ico" /Y
COPY "%~dp0A25\drf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.drf.ico" /Y
COPY "%~dp0A25\dxo.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dxo.ico" /Y
COPY "%~dp0A25\eip.ico" "%ProgramFiles%\PhotoQt\filetypes\image.eip.ico" /Y
COPY "%~dp0A25\epi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.epi.ico" /Y
COPY "%~dp0A25\eps.ico" "%ProgramFiles%\PhotoQt\filetypes\image.eps.ico" /Y
COPY "%~dp0A25\epsf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.epsf.ico" /Y
COPY "%~dp0A25\epsi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.epsi.ico" /Y
COPY "%~dp0A25\ept.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ept.ico" /Y
COPY "%~dp0A25\erf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.erf.ico" /Y
COPY "%~dp0A25\exr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.exr.ico" /Y
COPY "%~dp0A25\f4v.ico" "%ProgramFiles%\PhotoQt\filetypes\image.f4v.ico" /Y
COPY "%~dp0A25\ff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ff.ico" /Y
COPY "%~dp0A25\fff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fff.ico" /Y
COPY "%~dp0A25\fit.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fit.ico" /Y
COPY "%~dp0A25\fits.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fits.ico" /Y
COPY "%~dp0A25\fl32.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fl32.ico" /Y
COPY "%~dp0A25\flv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.flv.ico" /Y
COPY "%~dp0A25\fts.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fts.ico" /Y
COPY "%~dp0A25\ftx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ftx.ico" /Y
COPY "%~dp0A25\g3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.g3.ico" /Y
COPY "%~dp0A25\g4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.g4.ico" /Y
COPY "%~dp0A25\gg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.gg.ico" /Y
COPY "%~dp0A25\gif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.gif.ico" /Y
COPY "%~dp0A25\gig.ico" "%ProgramFiles%\PhotoQt\filetypes\image.gig.ico" /Y
COPY "%~dp0A25\gpr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.gpr.ico" /Y
COPY "%~dp0A25\hdp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.hdp.ico" /Y
COPY "%~dp0A25\hdr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.hdr.ico" /Y
COPY "%~dp0A25\heic.ico" "%ProgramFiles%\PhotoQt\filetypes\image.heic.ico" /Y
COPY "%~dp0A25\heif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.heif.ico" /Y
COPY "%~dp0A25\hrz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.hrz.ico" /Y
COPY "%~dp0A25\icb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.icb.ico" /Y
COPY "%~dp0A25\icns.ico" "%ProgramFiles%\PhotoQt\filetypes\image.icns.ico" /Y
COPY "%~dp0A25\ico.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ico.ico" /Y
COPY "%~dp0A25\iff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.iff.ico" /Y
COPY "%~dp0A25\iiq.ico" "%ProgramFiles%\PhotoQt\filetypes\image.iiq.ico" /Y
COPY "%~dp0A25\im1.ico" "%ProgramFiles%\PhotoQt\filetypes\image.im1.ico" /Y
COPY "%~dp0A25\im24.ico" "%ProgramFiles%\PhotoQt\filetypes\image.im24.ico" /Y
COPY "%~dp0A25\im32.ico" "%ProgramFiles%\PhotoQt\filetypes\image.im32.ico" /Y
COPY "%~dp0A25\im8.ico" "%ProgramFiles%\PhotoQt\filetypes\image.im8.ico" /Y
COPY "%~dp0A25\img.ico" "%ProgramFiles%\PhotoQt\filetypes\image.img.ico" /Y
COPY "%~dp0A25\inf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.inf.ico" /Y
COPY "%~dp0A25\j2k.ico" "%ProgramFiles%\PhotoQt\filetypes\image.j2k.ico" /Y
COPY "%~dp0A25\jbg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jbg.ico" /Y
COPY "%~dp0A25\jbig.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jbig.ico" /Y
COPY "%~dp0A25\jfif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jfif.ico" /Y
COPY "%~dp0A25\jif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jif.ico" /Y
COPY "%~dp0A25\jng.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jng.ico" /Y
COPY "%~dp0A25\jp2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jp2.ico" /Y
COPY "%~dp0A25\jpc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpc.ico" /Y
COPY "%~dp0A25\jpe.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpe.ico" /Y
COPY "%~dp0A25\jpeg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpeg.ico" /Y
COPY "%~dp0A25\jpeg2000.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpeg2000.ico" /Y
COPY "%~dp0A25\jpg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpg.ico" /Y
COPY "%~dp0A25\jpx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpx.ico" /Y
COPY "%~dp0A25\jxl.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jxl.ico" /Y
COPY "%~dp0A25\jxr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jxr.ico" /Y
COPY "%~dp0A25\k25.ico" "%ProgramFiles%\PhotoQt\filetypes\image.k25.ico" /Y
COPY "%~dp0A25\kc2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.kc2.ico" /Y
COPY "%~dp0A25\kdc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.kdc.ico" /Y
COPY "%~dp0A25\kla.ico" "%ProgramFiles%\PhotoQt\filetypes\image.kla.ico" /Y
COPY "%~dp0A25\koa.ico" "%ProgramFiles%\PhotoQt\filetypes\image.koa.ico" /Y
COPY "%~dp0A25\kra.ico" "%ProgramFiles%\PhotoQt\filetypes\image.kra.ico" /Y
COPY "%~dp0A25\lbm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.lbm.ico" /Y
COPY "%~dp0A25\liq.ico" "%ProgramFiles%\PhotoQt\filetypes\image.liq.ico" /Y
COPY "%~dp0A25\m2ts.ico" "%ProgramFiles%\PhotoQt\filetypes\image.m2ts.ico" /Y
COPY "%~dp0A25\m2v.ico" "%ProgramFiles%\PhotoQt\filetypes\image.m2v.ico" /Y
COPY "%~dp0A25\m4v.ico" "%ProgramFiles%\PhotoQt\filetypes\image.m4v.ico" /Y
COPY "%~dp0A25\mat.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mat.ico" /Y
COPY "%~dp0A25\mbfavs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mbfavs.ico" /Y
COPY "%~dp0A25\mdc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mdc.ico" /Y
COPY "%~dp0A25\mef.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mef.ico" /Y
COPY "%~dp0A25\mfw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mfw.ico" /Y
COPY "%~dp0A25\mif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mif.ico" /Y
COPY "%~dp0A25\miff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.miff.ico" /Y
COPY "%~dp0A25\mj2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mj2.ico" /Y
COPY "%~dp0A25\mkv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mkv.ico" /Y
COPY "%~dp0A25\mng.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mng.ico" /Y
COPY "%~dp0A25\mos.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mos.ico" /Y
COPY "%~dp0A25\mov.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mov.ico" /Y
COPY "%~dp0A25\mp2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mp2.ico" /Y
COPY "%~dp0A25\mp4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mp4.ico" /Y
COPY "%~dp0A25\mpc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpc.ico" /Y
COPY "%~dp0A25\mpe.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpe.ico" /Y
COPY "%~dp0A25\mpeg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpeg.ico" /Y
COPY "%~dp0A25\mpg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpg.ico" /Y
COPY "%~dp0A25\mpv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpv.ico" /Y
COPY "%~dp0A25\mrw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mrw.ico" /Y
COPY "%~dp0A25\mts.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mts.ico" /Y
COPY "%~dp0A25\mtv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mtv.ico" /Y
COPY "%~dp0A25\mvg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mvg.ico" /Y
COPY "%~dp0A25\mxf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mxf.ico" /Y
COPY "%~dp0A25\nef.ico" "%ProgramFiles%\PhotoQt\filetypes\image.nef.ico" /Y
COPY "%~dp0A25\nif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.nif.ico" /Y
COPY "%~dp0A25\nrw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.nrw.ico" /Y
COPY "%~dp0A25\obm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.obm.ico" /Y
COPY "%~dp0A25\ofm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ofm.ico" /Y
COPY "%~dp0A25\ogg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ogg.ico" /Y
COPY "%~dp0A25\ogv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ogv.ico" /Y
COPY "%~dp0A25\ora.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ora.ico" /Y
COPY "%~dp0A25\orf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.orf.ico" /Y
COPY "%~dp0A25\ori.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ori.ico" /Y
COPY "%~dp0A25\otb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.otb.ico" /Y
COPY "%~dp0A25\otc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.otc.ico" /Y
COPY "%~dp0A25\otf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.otf.ico" /Y
COPY "%~dp0A25\p7.ico" "%ProgramFiles%\PhotoQt\filetypes\image.p7.ico" /Y
COPY "%~dp0A25\pal.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pal.ico" /Y
COPY "%~dp0A25\palm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.palm.ico" /Y
COPY "%~dp0A25\pam.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pam.ico" /Y
COPY "%~dp0A25\pbm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pbm.ico" /Y
COPY "%~dp0A25\pcd.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pcd.ico" /Y
COPY "%~dp0A25\pcds.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pcds.ico" /Y
COPY "%~dp0A25\pct.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pct.ico" /Y
COPY "%~dp0A25\pcx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pcx.ico" /Y
COPY "%~dp0A25\pdb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pdb.ico" /Y
COPY "%~dp0A25\pdd.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pdd.ico" /Y
COPY "%~dp0A25\pdf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pdf.ico" /Y
COPY "%~dp0A25\pef.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pef.ico" /Y
COPY "%~dp0A25\pes.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pes.ico" /Y
COPY "%~dp0A25\pfa.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pfa.ico" /Y
COPY "%~dp0A25\pfb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pfb.ico" /Y
COPY "%~dp0A25\pfm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pfm.ico" /Y
COPY "%~dp0A25\pgm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pgm.ico" /Y
COPY "%~dp0A25\pgx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pgx.ico" /Y
COPY "%~dp0A25\phm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.phm.ico" /Y
COPY "%~dp0A25\pic.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pic.ico" /Y
COPY "%~dp0A25\picon.ico" "%ProgramFiles%\PhotoQt\filetypes\image.picon.ico" /Y
COPY "%~dp0A25\pict.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pict.ico" /Y
COPY "%~dp0A25\pix.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pix.ico" /Y
COPY "%~dp0A25\pm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pm.ico" /Y
COPY "%~dp0A25\png.ico" "%ProgramFiles%\PhotoQt\filetypes\image.png.ico" /Y
COPY "%~dp0A25\pnm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pnm.ico" /Y
COPY "%~dp0A25\ppm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ppm.ico" /Y
COPY "%~dp0A25\ps.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ps.ico" /Y
COPY "%~dp0A25\ps2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ps2.ico" /Y
COPY "%~dp0A25\ps3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ps3.ico" /Y
COPY "%~dp0A25\psb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.psb.ico" /Y
COPY "%~dp0A25\psd.ico" "%ProgramFiles%\PhotoQt\filetypes\image.psd.ico" /Y
COPY "%~dp0A25\psdt.ico" "%ProgramFiles%\PhotoQt\filetypes\image.psdt.ico" /Y
COPY "%~dp0A25\ptif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ptif.ico" /Y
COPY "%~dp0A25\ptiff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ptiff.ico" /Y
COPY "%~dp0A25\ptx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ptx.ico" /Y
COPY "%~dp0A25\pwm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pwm.ico" /Y
COPY "%~dp0A25\pwp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pwp.ico" /Y
COPY "%~dp0A25\pxn.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pxn.ico" /Y
COPY "%~dp0A25\pxr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pxr.ico" /Y
COPY "%~dp0A25\qoi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.qoi.ico" /Y
COPY "%~dp0A25\qt.ico" "%ProgramFiles%\PhotoQt\filetypes\image.qt.ico" /Y
COPY "%~dp0A25\qtk.ico" "%ProgramFiles%\PhotoQt\filetypes\image.qtk.ico" /Y
COPY "%~dp0A25\r3d.ico" "%ProgramFiles%\PhotoQt\filetypes\image.r3d.ico" /Y
COPY "%~dp0A25\rad.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rad.ico" /Y
COPY "%~dp0A25\raf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.raf.ico" /Y
COPY "%~dp0A25\rar.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rar.ico" /Y
COPY "%~dp0A25\ras.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ras.ico" /Y
COPY "%~dp0A25\rast.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rast.ico" /Y
COPY "%~dp0A25\raw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.raw.ico" /Y
COPY "%~dp0A25\rdc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rdc.ico" /Y
COPY "%~dp0A25\rgb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rgb.ico" /Y
COPY "%~dp0A25\rgba.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rgba.ico" /Y
COPY "%~dp0A25\rgbe.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rgbe.ico" /Y
COPY "%~dp0A25\rgf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rgf.ico" /Y
COPY "%~dp0A25\rla.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rla.ico" /Y
COPY "%~dp0A25\rle.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rle.ico" /Y
COPY "%~dp0A25\rm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rm.ico" /Y
COPY "%~dp0A25\rs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rs.ico" /Y
COPY "%~dp0A25\rw2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rw2.ico" /Y
COPY "%~dp0A25\rwl.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rwl.ico" /Y
COPY "%~dp0A25\rwz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rwz.ico" /Y
COPY "%~dp0A25\sai.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sai.ico" /Y
COPY "%~dp0A25\scr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.scr.ico" /Y
COPY "%~dp0A25\sct.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sct.ico" /Y
COPY "%~dp0A25\sfw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sfw.ico" /Y
COPY "%~dp0A25\sgi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sgi.ico" /Y
COPY "%~dp0A25\sixel.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sixel.ico" /Y
COPY "%~dp0A25\sr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sr.ico" /Y
COPY "%~dp0A25\sr2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sr2.ico" /Y
COPY "%~dp0A25\srf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.srf.ico" /Y
COPY "%~dp0A25\srw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.srw.ico" /Y
COPY "%~dp0A25\sti.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sti.ico" /Y
COPY "%~dp0A25\sun.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sun.ico" /Y
COPY "%~dp0A25\svg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.svg.ico" /Y
COPY "%~dp0A25\svgz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.svgz.ico" /Y
COPY "%~dp0A25\tar.bz2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.bz2.ico" /Y
COPY "%~dp0A25\tar.gz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.gz.ico" /Y
COPY "%~dp0A25\tar.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.ico" /Y
COPY "%~dp0A25\tar.lz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.lz.ico" /Y
COPY "%~dp0A25\tar.lzma.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.lzma.ico" /Y
COPY "%~dp0A25\tar.lzo.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.lzo.ico" /Y
COPY "%~dp0A25\tar.xz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.xz.ico" /Y
COPY "%~dp0A25\tar.zst.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.zst.ico" /Y
COPY "%~dp0A25\taz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.taz.ico" /Y
COPY "%~dp0A25\tb2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tb2.ico" /Y
COPY "%~dp0A25\tbz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tbz.ico" /Y
COPY "%~dp0A25\tbz2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tbz2.ico" /Y
COPY "%~dp0A25\tga.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tga.ico" /Y
COPY "%~dp0A25\tgz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tgz.ico" /Y
COPY "%~dp0A25\tif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tif.ico" /Y
COPY "%~dp0A25\tiff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tiff.ico" /Y
COPY "%~dp0A25\tim.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tim.ico" /Y
COPY "%~dp0A25\tlz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tlz.ico" /Y
COPY "%~dp0A25\ts.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ts.ico" /Y
COPY "%~dp0A25\ttc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ttc.ico" /Y
COPY "%~dp0A25\ttf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ttf.ico" /Y
COPY "%~dp0A25\txz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.txz.ico" /Y
COPY "%~dp0A25\tZ.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tZ.ico" /Y
COPY "%~dp0A25\tz2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tz2.ico" /Y
COPY "%~dp0A25\tzst.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tzst.ico" /Y
COPY "%~dp0A25\unknown.ico" "%ProgramFiles%\PhotoQt\filetypes\image.unknown.ico" /Y
COPY "%~dp0A25\vda.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vda.ico" /Y
COPY "%~dp0A25\vic.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vic.ico" /Y
COPY "%~dp0A25\vicar.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vicar.ico" /Y
COPY "%~dp0A25\viff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.viff.ico" /Y
COPY "%~dp0A25\vob.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vob.ico" /Y
COPY "%~dp0A25\vst.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vst.ico" /Y
COPY "%~dp0A25\vtf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vtf.ico" /Y
COPY "%~dp0A25\wbmp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wbmp.ico" /Y
COPY "%~dp0A25\wdp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wdp.ico" /Y
COPY "%~dp0A25\webm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.webm.ico" /Y
COPY "%~dp0A25\webp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.webp.ico" /Y
COPY "%~dp0A25\wmf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wmf.ico" /Y
COPY "%~dp0A25\wmv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wmv.ico" /Y
COPY "%~dp0A25\wmz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wmz.ico" /Y
COPY "%~dp0A25\wpg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wpg.ico" /Y
COPY "%~dp0A25\x.ico" "%ProgramFiles%\PhotoQt\filetypes\image.x.ico" /Y
COPY "%~dp0A25\x3f.ico" "%ProgramFiles%\PhotoQt\filetypes\image.x3f.ico" /Y
COPY "%~dp0A25\xbm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xbm.ico" /Y
COPY "%~dp0A25\xcf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xcf.ico" /Y
COPY "%~dp0A25\xpm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xpm.ico" /Y
COPY "%~dp0A25\xv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xv.ico" /Y
COPY "%~dp0A25\xwd.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xwd.ico" /Y
COPY "%~dp0A25\zip.ico" "%ProgramFiles%\PhotoQt\filetypes\image.zip.ico" /Y
