@ECHO OFF
COPY "%~dp0A26\3fr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.3fr.ico" /Y
COPY "%~dp0A26\3g2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.3g2.ico" /Y
COPY "%~dp0A26\3gp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.3gp.ico" /Y
COPY "%~dp0A26\7z.ico" "%ProgramFiles%\PhotoQt\filetypes\image.7z.ico" /Y
COPY "%~dp0A26\aai.ico" "%ProgramFiles%\PhotoQt\filetypes\image.aai.ico" /Y
COPY "%~dp0A26\afm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.afm.ico" /Y
COPY "%~dp0A26\ai.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ai.ico" /Y
COPY "%~dp0A26\alb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.alb.ico" /Y
COPY "%~dp0A26\alias.ico" "%ProgramFiles%\PhotoQt\filetypes\image.alias.ico" /Y
COPY "%~dp0A26\als.ico" "%ProgramFiles%\PhotoQt\filetypes\image.als.ico" /Y
COPY "%~dp0A26\amv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.amv.ico" /Y
COPY "%~dp0A26\ani.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ani.ico" /Y
COPY "%~dp0A26\apm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.apm.ico" /Y
COPY "%~dp0A26\apng.ico" "%ProgramFiles%\PhotoQt\filetypes\image.apng.ico" /Y
COPY "%~dp0A26\ari.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ari.ico" /Y
COPY "%~dp0A26\arq.ico" "%ProgramFiles%\PhotoQt\filetypes\image.arq.ico" /Y
COPY "%~dp0A26\art.ico" "%ProgramFiles%\PhotoQt\filetypes\image.art.ico" /Y
COPY "%~dp0A26\arw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.arw.ico" /Y
COPY "%~dp0A26\asf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.asf.ico" /Y
COPY "%~dp0A26\avi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.avi.ico" /Y
COPY "%~dp0A26\avif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.avif.ico" /Y
COPY "%~dp0A26\avifs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.avifs.ico" /Y
COPY "%~dp0A26\avs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.avs.ico" /Y
COPY "%~dp0A26\bay.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bay.ico" /Y
COPY "%~dp0A26\bie.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bie.ico" /Y
COPY "%~dp0A26\bm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bm.ico" /Y
COPY "%~dp0A26\bmp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bmp.ico" /Y
COPY "%~dp0A26\bmq.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bmq.ico" /Y
COPY "%~dp0A26\bpg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bpg.ico" /Y
COPY "%~dp0A26\bw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.bw.ico" /Y
COPY "%~dp0A26\c4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.c4.ico" /Y
COPY "%~dp0A26\cal.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cal.ico" /Y
COPY "%~dp0A26\cals.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cals.ico" /Y
COPY "%~dp0A26\cap.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cap.ico" /Y
COPY "%~dp0A26\cb7.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cb7.ico" /Y
COPY "%~dp0A26\cbr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cbr.ico" /Y
COPY "%~dp0A26\cbt.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cbt.ico" /Y
COPY "%~dp0A26\cbz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cbz.ico" /Y
COPY "%~dp0A26\cg3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cg3.ico" /Y
COPY "%~dp0A26\cg4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cg4.ico" /Y
COPY "%~dp0A26\ch.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ch.ico" /Y
COPY "%~dp0A26\cine.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cine.ico" /Y
COPY "%~dp0A26\cr2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cr2.ico" /Y
COPY "%~dp0A26\cr3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cr3.ico" /Y
COPY "%~dp0A26\crr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.crr.ico" /Y
COPY "%~dp0A26\crw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.crw.ico" /Y
COPY "%~dp0A26\cs1.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cs1.ico" /Y
COPY "%~dp0A26\ct.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct.ico" /Y
COPY "%~dp0A26\ct1.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct1.ico" /Y
COPY "%~dp0A26\ct2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct2.ico" /Y
COPY "%~dp0A26\ct3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct3.ico" /Y
COPY "%~dp0A26\ct4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ct4.ico" /Y
COPY "%~dp0A26\cube.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cube.ico" /Y
COPY "%~dp0A26\cur.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cur.ico" /Y
COPY "%~dp0A26\cut.ico" "%ProgramFiles%\PhotoQt\filetypes\image.cut.ico" /Y
COPY "%~dp0A26\dc2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dc2.ico" /Y
COPY "%~dp0A26\dcm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dcm.ico" /Y
COPY "%~dp0A26\dcr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dcr.ico" /Y
COPY "%~dp0A26\dcs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dcs.ico" /Y
COPY "%~dp0A26\dcx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dcx.ico" /Y
COPY "%~dp0A26\dds.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dds.ico" /Y
COPY "%~dp0A26\dfont.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dfont.ico" /Y
COPY "%~dp0A26\dib.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dib.ico" /Y
COPY "%~dp0A26\dic.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dic.ico" /Y
COPY "%~dp0A26\djv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.djv.ico" /Y
COPY "%~dp0A26\djvu.ico" "%ProgramFiles%\PhotoQt\filetypes\image.djvu.ico" /Y
COPY "%~dp0A26\dng.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dng.ico" /Y
COPY "%~dp0A26\dpx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dpx.ico" /Y
COPY "%~dp0A26\drf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.drf.ico" /Y
COPY "%~dp0A26\dxo.ico" "%ProgramFiles%\PhotoQt\filetypes\image.dxo.ico" /Y
COPY "%~dp0A26\eip.ico" "%ProgramFiles%\PhotoQt\filetypes\image.eip.ico" /Y
COPY "%~dp0A26\epi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.epi.ico" /Y
COPY "%~dp0A26\eps.ico" "%ProgramFiles%\PhotoQt\filetypes\image.eps.ico" /Y
COPY "%~dp0A26\epsf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.epsf.ico" /Y
COPY "%~dp0A26\epsi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.epsi.ico" /Y
COPY "%~dp0A26\ept.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ept.ico" /Y
COPY "%~dp0A26\erf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.erf.ico" /Y
COPY "%~dp0A26\exr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.exr.ico" /Y
COPY "%~dp0A26\f4v.ico" "%ProgramFiles%\PhotoQt\filetypes\image.f4v.ico" /Y
COPY "%~dp0A26\ff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ff.ico" /Y
COPY "%~dp0A26\fff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fff.ico" /Y
COPY "%~dp0A26\fit.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fit.ico" /Y
COPY "%~dp0A26\fits.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fits.ico" /Y
COPY "%~dp0A26\fl32.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fl32.ico" /Y
COPY "%~dp0A26\flv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.flv.ico" /Y
COPY "%~dp0A26\fts.ico" "%ProgramFiles%\PhotoQt\filetypes\image.fts.ico" /Y
COPY "%~dp0A26\ftx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ftx.ico" /Y
COPY "%~dp0A26\g3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.g3.ico" /Y
COPY "%~dp0A26\g4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.g4.ico" /Y
COPY "%~dp0A26\gg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.gg.ico" /Y
COPY "%~dp0A26\gif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.gif.ico" /Y
COPY "%~dp0A26\gig.ico" "%ProgramFiles%\PhotoQt\filetypes\image.gig.ico" /Y
COPY "%~dp0A26\gpr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.gpr.ico" /Y
COPY "%~dp0A26\hdp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.hdp.ico" /Y
COPY "%~dp0A26\hdr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.hdr.ico" /Y
COPY "%~dp0A26\heic.ico" "%ProgramFiles%\PhotoQt\filetypes\image.heic.ico" /Y
COPY "%~dp0A26\heif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.heif.ico" /Y
COPY "%~dp0A26\hrz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.hrz.ico" /Y
COPY "%~dp0A26\icb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.icb.ico" /Y
COPY "%~dp0A26\icns.ico" "%ProgramFiles%\PhotoQt\filetypes\image.icns.ico" /Y
COPY "%~dp0A26\ico.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ico.ico" /Y
COPY "%~dp0A26\iff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.iff.ico" /Y
COPY "%~dp0A26\iiq.ico" "%ProgramFiles%\PhotoQt\filetypes\image.iiq.ico" /Y
COPY "%~dp0A26\im1.ico" "%ProgramFiles%\PhotoQt\filetypes\image.im1.ico" /Y
COPY "%~dp0A26\im24.ico" "%ProgramFiles%\PhotoQt\filetypes\image.im24.ico" /Y
COPY "%~dp0A26\im32.ico" "%ProgramFiles%\PhotoQt\filetypes\image.im32.ico" /Y
COPY "%~dp0A26\im8.ico" "%ProgramFiles%\PhotoQt\filetypes\image.im8.ico" /Y
COPY "%~dp0A26\img.ico" "%ProgramFiles%\PhotoQt\filetypes\image.img.ico" /Y
COPY "%~dp0A26\inf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.inf.ico" /Y
COPY "%~dp0A26\j2k.ico" "%ProgramFiles%\PhotoQt\filetypes\image.j2k.ico" /Y
COPY "%~dp0A26\jbg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jbg.ico" /Y
COPY "%~dp0A26\jbig.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jbig.ico" /Y
COPY "%~dp0A26\jfif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jfif.ico" /Y
COPY "%~dp0A26\jif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jif.ico" /Y
COPY "%~dp0A26\jng.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jng.ico" /Y
COPY "%~dp0A26\jp2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jp2.ico" /Y
COPY "%~dp0A26\jpc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpc.ico" /Y
COPY "%~dp0A26\jpe.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpe.ico" /Y
COPY "%~dp0A26\jpeg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpeg.ico" /Y
COPY "%~dp0A26\jpeg2000.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpeg2000.ico" /Y
COPY "%~dp0A26\jpg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpg.ico" /Y
COPY "%~dp0A26\jpx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jpx.ico" /Y
COPY "%~dp0A26\jxl.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jxl.ico" /Y
COPY "%~dp0A26\jxr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.jxr.ico" /Y
COPY "%~dp0A26\k25.ico" "%ProgramFiles%\PhotoQt\filetypes\image.k25.ico" /Y
COPY "%~dp0A26\kc2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.kc2.ico" /Y
COPY "%~dp0A26\kdc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.kdc.ico" /Y
COPY "%~dp0A26\kla.ico" "%ProgramFiles%\PhotoQt\filetypes\image.kla.ico" /Y
COPY "%~dp0A26\koa.ico" "%ProgramFiles%\PhotoQt\filetypes\image.koa.ico" /Y
COPY "%~dp0A26\kra.ico" "%ProgramFiles%\PhotoQt\filetypes\image.kra.ico" /Y
COPY "%~dp0A26\lbm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.lbm.ico" /Y
COPY "%~dp0A26\liq.ico" "%ProgramFiles%\PhotoQt\filetypes\image.liq.ico" /Y
COPY "%~dp0A26\m2ts.ico" "%ProgramFiles%\PhotoQt\filetypes\image.m2ts.ico" /Y
COPY "%~dp0A26\m2v.ico" "%ProgramFiles%\PhotoQt\filetypes\image.m2v.ico" /Y
COPY "%~dp0A26\m4v.ico" "%ProgramFiles%\PhotoQt\filetypes\image.m4v.ico" /Y
COPY "%~dp0A26\mat.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mat.ico" /Y
COPY "%~dp0A26\mbfavs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mbfavs.ico" /Y
COPY "%~dp0A26\mdc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mdc.ico" /Y
COPY "%~dp0A26\mef.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mef.ico" /Y
COPY "%~dp0A26\mfw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mfw.ico" /Y
COPY "%~dp0A26\mif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mif.ico" /Y
COPY "%~dp0A26\miff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.miff.ico" /Y
COPY "%~dp0A26\mj2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mj2.ico" /Y
COPY "%~dp0A26\mkv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mkv.ico" /Y
COPY "%~dp0A26\mng.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mng.ico" /Y
COPY "%~dp0A26\mos.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mos.ico" /Y
COPY "%~dp0A26\mov.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mov.ico" /Y
COPY "%~dp0A26\mp2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mp2.ico" /Y
COPY "%~dp0A26\mp4.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mp4.ico" /Y
COPY "%~dp0A26\mpc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpc.ico" /Y
COPY "%~dp0A26\mpe.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpe.ico" /Y
COPY "%~dp0A26\mpeg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpeg.ico" /Y
COPY "%~dp0A26\mpg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpg.ico" /Y
COPY "%~dp0A26\mpv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mpv.ico" /Y
COPY "%~dp0A26\mrw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mrw.ico" /Y
COPY "%~dp0A26\mts.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mts.ico" /Y
COPY "%~dp0A26\mtv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mtv.ico" /Y
COPY "%~dp0A26\mvg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mvg.ico" /Y
COPY "%~dp0A26\mxf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.mxf.ico" /Y
COPY "%~dp0A26\nef.ico" "%ProgramFiles%\PhotoQt\filetypes\image.nef.ico" /Y
COPY "%~dp0A26\nif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.nif.ico" /Y
COPY "%~dp0A26\nrw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.nrw.ico" /Y
COPY "%~dp0A26\obm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.obm.ico" /Y
COPY "%~dp0A26\ofm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ofm.ico" /Y
COPY "%~dp0A26\ogg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ogg.ico" /Y
COPY "%~dp0A26\ogv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ogv.ico" /Y
COPY "%~dp0A26\ora.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ora.ico" /Y
COPY "%~dp0A26\orf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.orf.ico" /Y
COPY "%~dp0A26\ori.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ori.ico" /Y
COPY "%~dp0A26\otb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.otb.ico" /Y
COPY "%~dp0A26\otc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.otc.ico" /Y
COPY "%~dp0A26\otf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.otf.ico" /Y
COPY "%~dp0A26\p7.ico" "%ProgramFiles%\PhotoQt\filetypes\image.p7.ico" /Y
COPY "%~dp0A26\pal.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pal.ico" /Y
COPY "%~dp0A26\palm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.palm.ico" /Y
COPY "%~dp0A26\pam.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pam.ico" /Y
COPY "%~dp0A26\pbm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pbm.ico" /Y
COPY "%~dp0A26\pcd.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pcd.ico" /Y
COPY "%~dp0A26\pcds.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pcds.ico" /Y
COPY "%~dp0A26\pct.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pct.ico" /Y
COPY "%~dp0A26\pcx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pcx.ico" /Y
COPY "%~dp0A26\pdb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pdb.ico" /Y
COPY "%~dp0A26\pdd.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pdd.ico" /Y
COPY "%~dp0A26\pdf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pdf.ico" /Y
COPY "%~dp0A26\pef.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pef.ico" /Y
COPY "%~dp0A26\pes.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pes.ico" /Y
COPY "%~dp0A26\pfa.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pfa.ico" /Y
COPY "%~dp0A26\pfb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pfb.ico" /Y
COPY "%~dp0A26\pfm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pfm.ico" /Y
COPY "%~dp0A26\pgm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pgm.ico" /Y
COPY "%~dp0A26\pgx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pgx.ico" /Y
COPY "%~dp0A26\phm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.phm.ico" /Y
COPY "%~dp0A26\pic.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pic.ico" /Y
COPY "%~dp0A26\picon.ico" "%ProgramFiles%\PhotoQt\filetypes\image.picon.ico" /Y
COPY "%~dp0A26\pict.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pict.ico" /Y
COPY "%~dp0A26\pix.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pix.ico" /Y
COPY "%~dp0A26\pm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pm.ico" /Y
COPY "%~dp0A26\png.ico" "%ProgramFiles%\PhotoQt\filetypes\image.png.ico" /Y
COPY "%~dp0A26\pnm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pnm.ico" /Y
COPY "%~dp0A26\ppm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ppm.ico" /Y
COPY "%~dp0A26\ps.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ps.ico" /Y
COPY "%~dp0A26\ps2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ps2.ico" /Y
COPY "%~dp0A26\ps3.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ps3.ico" /Y
COPY "%~dp0A26\psb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.psb.ico" /Y
COPY "%~dp0A26\psd.ico" "%ProgramFiles%\PhotoQt\filetypes\image.psd.ico" /Y
COPY "%~dp0A26\psdt.ico" "%ProgramFiles%\PhotoQt\filetypes\image.psdt.ico" /Y
COPY "%~dp0A26\ptif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ptif.ico" /Y
COPY "%~dp0A26\ptiff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ptiff.ico" /Y
COPY "%~dp0A26\ptx.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ptx.ico" /Y
COPY "%~dp0A26\pwm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pwm.ico" /Y
COPY "%~dp0A26\pwp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pwp.ico" /Y
COPY "%~dp0A26\pxn.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pxn.ico" /Y
COPY "%~dp0A26\pxr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.pxr.ico" /Y
COPY "%~dp0A26\qoi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.qoi.ico" /Y
COPY "%~dp0A26\qt.ico" "%ProgramFiles%\PhotoQt\filetypes\image.qt.ico" /Y
COPY "%~dp0A26\qtk.ico" "%ProgramFiles%\PhotoQt\filetypes\image.qtk.ico" /Y
COPY "%~dp0A26\r3d.ico" "%ProgramFiles%\PhotoQt\filetypes\image.r3d.ico" /Y
COPY "%~dp0A26\rad.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rad.ico" /Y
COPY "%~dp0A26\raf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.raf.ico" /Y
COPY "%~dp0A26\rar.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rar.ico" /Y
COPY "%~dp0A26\ras.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ras.ico" /Y
COPY "%~dp0A26\rast.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rast.ico" /Y
COPY "%~dp0A26\raw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.raw.ico" /Y
COPY "%~dp0A26\rdc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rdc.ico" /Y
COPY "%~dp0A26\rgb.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rgb.ico" /Y
COPY "%~dp0A26\rgba.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rgba.ico" /Y
COPY "%~dp0A26\rgbe.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rgbe.ico" /Y
COPY "%~dp0A26\rgf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rgf.ico" /Y
COPY "%~dp0A26\rla.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rla.ico" /Y
COPY "%~dp0A26\rle.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rle.ico" /Y
COPY "%~dp0A26\rm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rm.ico" /Y
COPY "%~dp0A26\rs.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rs.ico" /Y
COPY "%~dp0A26\rw2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rw2.ico" /Y
COPY "%~dp0A26\rwl.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rwl.ico" /Y
COPY "%~dp0A26\rwz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.rwz.ico" /Y
COPY "%~dp0A26\sai.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sai.ico" /Y
COPY "%~dp0A26\scr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.scr.ico" /Y
COPY "%~dp0A26\sct.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sct.ico" /Y
COPY "%~dp0A26\sfw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sfw.ico" /Y
COPY "%~dp0A26\sgi.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sgi.ico" /Y
COPY "%~dp0A26\sixel.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sixel.ico" /Y
COPY "%~dp0A26\sr.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sr.ico" /Y
COPY "%~dp0A26\sr2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sr2.ico" /Y
COPY "%~dp0A26\srf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.srf.ico" /Y
COPY "%~dp0A26\srw.ico" "%ProgramFiles%\PhotoQt\filetypes\image.srw.ico" /Y
COPY "%~dp0A26\sti.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sti.ico" /Y
COPY "%~dp0A26\sun.ico" "%ProgramFiles%\PhotoQt\filetypes\image.sun.ico" /Y
COPY "%~dp0A26\svg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.svg.ico" /Y
COPY "%~dp0A26\svgz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.svgz.ico" /Y
COPY "%~dp0A26\tar.bz2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.bz2.ico" /Y
COPY "%~dp0A26\tar.gz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.gz.ico" /Y
COPY "%~dp0A26\tar.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.ico" /Y
COPY "%~dp0A26\tar.lz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.lz.ico" /Y
COPY "%~dp0A26\tar.lzma.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.lzma.ico" /Y
COPY "%~dp0A26\tar.lzo.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.lzo.ico" /Y
COPY "%~dp0A26\tar.xz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.xz.ico" /Y
COPY "%~dp0A26\tar.zst.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tar.zst.ico" /Y
COPY "%~dp0A26\taz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.taz.ico" /Y
COPY "%~dp0A26\tb2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tb2.ico" /Y
COPY "%~dp0A26\tbz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tbz.ico" /Y
COPY "%~dp0A26\tbz2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tbz2.ico" /Y
COPY "%~dp0A26\tga.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tga.ico" /Y
COPY "%~dp0A26\tgz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tgz.ico" /Y
COPY "%~dp0A26\tif.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tif.ico" /Y
COPY "%~dp0A26\tiff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tiff.ico" /Y
COPY "%~dp0A26\tim.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tim.ico" /Y
COPY "%~dp0A26\tlz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tlz.ico" /Y
COPY "%~dp0A26\ts.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ts.ico" /Y
COPY "%~dp0A26\ttc.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ttc.ico" /Y
COPY "%~dp0A26\ttf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.ttf.ico" /Y
COPY "%~dp0A26\txz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.txz.ico" /Y
COPY "%~dp0A26\tZ.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tZ.ico" /Y
COPY "%~dp0A26\tz2.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tz2.ico" /Y
COPY "%~dp0A26\tzst.ico" "%ProgramFiles%\PhotoQt\filetypes\image.tzst.ico" /Y
COPY "%~dp0A26\unknown.ico" "%ProgramFiles%\PhotoQt\filetypes\image.unknown.ico" /Y
COPY "%~dp0A26\vda.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vda.ico" /Y
COPY "%~dp0A26\vic.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vic.ico" /Y
COPY "%~dp0A26\vicar.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vicar.ico" /Y
COPY "%~dp0A26\viff.ico" "%ProgramFiles%\PhotoQt\filetypes\image.viff.ico" /Y
COPY "%~dp0A26\vob.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vob.ico" /Y
COPY "%~dp0A26\vst.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vst.ico" /Y
COPY "%~dp0A26\vtf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.vtf.ico" /Y
COPY "%~dp0A26\wbmp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wbmp.ico" /Y
COPY "%~dp0A26\wdp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wdp.ico" /Y
COPY "%~dp0A26\webm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.webm.ico" /Y
COPY "%~dp0A26\webp.ico" "%ProgramFiles%\PhotoQt\filetypes\image.webp.ico" /Y
COPY "%~dp0A26\wmf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wmf.ico" /Y
COPY "%~dp0A26\wmv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wmv.ico" /Y
COPY "%~dp0A26\wmz.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wmz.ico" /Y
COPY "%~dp0A26\wpg.ico" "%ProgramFiles%\PhotoQt\filetypes\image.wpg.ico" /Y
COPY "%~dp0A26\x.ico" "%ProgramFiles%\PhotoQt\filetypes\image.x.ico" /Y
COPY "%~dp0A26\x3f.ico" "%ProgramFiles%\PhotoQt\filetypes\image.x3f.ico" /Y
COPY "%~dp0A26\xbm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xbm.ico" /Y
COPY "%~dp0A26\xcf.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xcf.ico" /Y
COPY "%~dp0A26\xpm.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xpm.ico" /Y
COPY "%~dp0A26\xv.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xv.ico" /Y
COPY "%~dp0A26\xwd.ico" "%ProgramFiles%\PhotoQt\filetypes\image.xwd.ico" /Y
COPY "%~dp0A26\zip.ico" "%ProgramFiles%\PhotoQt\filetypes\image.zip.ico" /Y
