@ECHO OFF
COPY "%~dp0A26\3FR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\3fr.ico" /Y
COPY "%~dp0A26\ARI.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\ari.ico" /Y
COPY "%~dp0A26\ARW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\arw.ico" /Y
COPY "%~dp0A26\AVIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\avif.ico" /Y
COPY "%~dp0A26\B64.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\b64.ico" /Y
COPY "%~dp0A26\BAY.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\bay.ico" /Y
COPY "%~dp0A26\BMP.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\bmp.ico" /Y
COPY "%~dp0A26\CAP.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cap.ico" /Y
COPY "%~dp0A26\CR2.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cr2.ico" /Y
COPY "%~dp0A26\CR3.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cr3.ico" /Y
COPY "%~dp0A26\CRW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\crw.ico" /Y
COPY "%~dp0A26\CUR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cur.ico" /Y
COPY "%~dp0A26\CUT.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\cut.ico" /Y
COPY "%~dp0A26\DATA.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\data.ico" /Y
COPY "%~dp0A26\DCR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dcr.ico" /Y
COPY "%~dp0A26\DCS.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dcs.ico" /Y
COPY "%~dp0A26\DDS.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dds.ico" /Y
COPY "%~dp0A26\DIB.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dib.ico" /Y
COPY "%~dp0A26\DNG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\dng.ico" /Y
COPY "%~dp0A26\DRF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\drf.ico" /Y
COPY "%~dp0A26\EIP.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\eip.ico" /Y
COPY "%~dp0A26\EMF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\emf.ico" /Y
COPY "%~dp0A26\ERF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\erf.ico" /Y
COPY "%~dp0A26\EXIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\exif.ico" /Y
COPY "%~dp0A26\EXR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\exr.ico" /Y
COPY "%~dp0A26\FFF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\fff.ico" /Y
COPY "%~dp0A26\GIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\gif.ico" /Y
COPY "%~dp0A26\GPR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\gpr.ico" /Y
COPY "%~dp0A26\HDR.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\hdr.ico" /Y
COPY "%~dp0A26\HEIC.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\heic.ico" /Y
COPY "%~dp0A26\HEIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\heif.ico" /Y
COPY "%~dp0A26\ICO.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\ico.ico" /Y
COPY "%~dp0A26\IIQ.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\iiq.ico" /Y
COPY "%~dp0A26\JFIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jfif.ico" /Y
COPY "%~dp0A26\JPE.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jpe.ico" /Y
COPY "%~dp0A26\JPEG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jpeg.ico" /Y
COPY "%~dp0A26\JPG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jpg.ico" /Y
COPY "%~dp0A26\JXL.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\jxl.ico" /Y
COPY "%~dp0A26\K25.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\k25.ico" /Y
COPY "%~dp0A26\KDC.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\kdc.ico" /Y
COPY "%~dp0A26\MDC.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\mdc.ico" /Y
COPY "%~dp0A26\MEF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\mef.ico" /Y
COPY "%~dp0A26\MOS.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\mos.ico" /Y
COPY "%~dp0A26\MRW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\mrw.ico" /Y
COPY "%~dp0A26\NEF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\nef.ico" /Y
COPY "%~dp0A26\NRW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\nrw.ico" /Y
COPY "%~dp0A26\OBM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\obm.ico" /Y
COPY "%~dp0A26\ORF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\orf.ico" /Y
COPY "%~dp0A26\PBM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pbm.ico" /Y
COPY "%~dp0A26\PCX.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pcx.ico" /Y
COPY "%~dp0A26\PEF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pef.ico" /Y
COPY "%~dp0A26\PGM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pgm.ico" /Y
COPY "%~dp0A26\PNG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\png.ico" /Y
COPY "%~dp0A26\PPM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\ppm.ico" /Y
COPY "%~dp0A26\PSD.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\psd.ico" /Y
COPY "%~dp0A26\PTX.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\ptx.ico" /Y
COPY "%~dp0A26\PXN.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\pxn.ico" /Y
COPY "%~dp0A26\QOI.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\qoi.ico" /Y
COPY "%~dp0A26\R3D.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\r3d.ico" /Y
COPY "%~dp0A26\RAF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\raf.ico" /Y
COPY "%~dp0A26\RAW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\raw.ico" /Y
COPY "%~dp0A26\RW2.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\rw2.ico" /Y
COPY "%~dp0A26\RWL.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\rwl.ico" /Y
COPY "%~dp0A26\RWZ.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\rwz.ico" /Y
COPY "%~dp0A26\SR2.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\sr2.ico" /Y
COPY "%~dp0A26\SRF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\srf.ico" /Y
COPY "%~dp0A26\SRW.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\srw.ico" /Y
COPY "%~dp0A26\SVG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\svg.ico" /Y
COPY "%~dp0A26\TGA.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\tga.ico" /Y
COPY "%~dp0A26\TIF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\tif.ico" /Y
COPY "%~dp0A26\TIFF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\tiff.ico" /Y
COPY "%~dp0A26\WEBP.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\webp.ico" /Y
COPY "%~dp0A26\WIC.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\wic.ico" /Y
COPY "%~dp0A26\WMF.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\wmf.ico" /Y
COPY "%~dp0A26\WPG.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\wpg.ico" /Y
COPY "%~dp0A26\X3F.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\x3f.ico" /Y
COPY "%~dp0A26\XBM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\xbm.ico" /Y
COPY "%~dp0A26\XPM.ico" "%LocalAppData%\Programs\ImageGlass\Ext-Icons\xpm.ico" /Y
