@ECHO OFF
MD "%~dp0Ext-Icons"
COPY "%~dp0Icons\3FR.ico" "%~dp0Ext-Icons\3fr.ico" /Y
COPY "%~dp0Icons\ARI.ico" "%~dp0Ext-Icons\ari.ico" /Y
COPY "%~dp0Icons\ARW.ico" "%~dp0Ext-Icons\arw.ico" /Y
COPY "%~dp0Icons\AVIF.ico" "%~dp0Ext-Icons\avif.ico" /Y
COPY "%~dp0Icons\B64.ico" "%~dp0Ext-Icons\b64.ico" /Y
COPY "%~dp0Icons\BAY.ico" "%~dp0Ext-Icons\bay.ico" /Y
COPY "%~dp0Icons\BMP.ico" "%~dp0Ext-Icons\bmp.ico" /Y
COPY "%~dp0Icons\CAP.ico" "%~dp0Ext-Icons\cap.ico" /Y
COPY "%~dp0Icons\CR2.ico" "%~dp0Ext-Icons\cr2.ico" /Y
COPY "%~dp0Icons\CR3.ico" "%~dp0Ext-Icons\cr3.ico" /Y
COPY "%~dp0Icons\CRW.ico" "%~dp0Ext-Icons\crw.ico" /Y
COPY "%~dp0Icons\CUR.ico" "%~dp0Ext-Icons\cur.ico" /Y
COPY "%~dp0Icons\CUT.ico" "%~dp0Ext-Icons\cut.ico" /Y
COPY "%~dp0Icons\DATA.ico" "%~dp0Ext-Icons\data.ico" /Y
COPY "%~dp0Icons\DCR.ico" "%~dp0Ext-Icons\dcr.ico" /Y
COPY "%~dp0Icons\DCS.ico" "%~dp0Ext-Icons\dcs.ico" /Y
COPY "%~dp0Icons\DDS.ico" "%~dp0Ext-Icons\dds.ico" /Y
COPY "%~dp0Icons\DIB.ico" "%~dp0Ext-Icons\dib.ico" /Y
COPY "%~dp0Icons\DNG.ico" "%~dp0Ext-Icons\dng.ico" /Y
COPY "%~dp0Icons\DRF.ico" "%~dp0Ext-Icons\drf.ico" /Y
COPY "%~dp0Icons\EIP.ico" "%~dp0Ext-Icons\eip.ico" /Y
COPY "%~dp0Icons\EMF.ico" "%~dp0Ext-Icons\emf.ico" /Y
COPY "%~dp0Icons\ERF.ico" "%~dp0Ext-Icons\erf.ico" /Y
COPY "%~dp0Icons\EXIF.ico" "%~dp0Ext-Icons\exif.ico" /Y
COPY "%~dp0Icons\EXR.ico" "%~dp0Ext-Icons\exr.ico" /Y
COPY "%~dp0Icons\FFF.ico" "%~dp0Ext-Icons\fff.ico" /Y
COPY "%~dp0Icons\GIF.ico" "%~dp0Ext-Icons\gif.ico" /Y
COPY "%~dp0Icons\GPR.ico" "%~dp0Ext-Icons\gpr.ico" /Y
COPY "%~dp0Icons\HDR.ico" "%~dp0Ext-Icons\hdr.ico" /Y
COPY "%~dp0Icons\HEIC.ico" "%~dp0Ext-Icons\heic.ico" /Y
COPY "%~dp0Icons\HEIF.ico" "%~dp0Ext-Icons\heif.ico" /Y
COPY "%~dp0Icons\ICO.ico" "%~dp0Ext-Icons\ico.ico" /Y
COPY "%~dp0Icons\IIQ.ico" "%~dp0Ext-Icons\iiq.ico" /Y
COPY "%~dp0Icons\JFIF.ico" "%~dp0Ext-Icons\jfif.ico" /Y
COPY "%~dp0Icons\JPE.ico" "%~dp0Ext-Icons\jpe.ico" /Y
COPY "%~dp0Icons\JPEG.ico" "%~dp0Ext-Icons\jpeg.ico" /Y
COPY "%~dp0Icons\JPG.ico" "%~dp0Ext-Icons\jpg.ico" /Y
COPY "%~dp0Icons\JXL.ico" "%~dp0Ext-Icons\jxl.ico" /Y
COPY "%~dp0Icons\K25.ico" "%~dp0Ext-Icons\k25.ico" /Y
COPY "%~dp0Icons\KDC.ico" "%~dp0Ext-Icons\kdc.ico" /Y
COPY "%~dp0Icons\MDC.ico" "%~dp0Ext-Icons\mdc.ico" /Y
COPY "%~dp0Icons\MEF.ico" "%~dp0Ext-Icons\mef.ico" /Y
COPY "%~dp0Icons\MOS.ico" "%~dp0Ext-Icons\mos.ico" /Y
COPY "%~dp0Icons\MRW.ico" "%~dp0Ext-Icons\mrw.ico" /Y
COPY "%~dp0Icons\NEF.ico" "%~dp0Ext-Icons\nef.ico" /Y
COPY "%~dp0Icons\NRW.ico" "%~dp0Ext-Icons\nrw.ico" /Y
COPY "%~dp0Icons\OBM.ico" "%~dp0Ext-Icons\obm.ico" /Y
COPY "%~dp0Icons\ORF.ico" "%~dp0Ext-Icons\orf.ico" /Y
COPY "%~dp0Icons\PBM.ico" "%~dp0Ext-Icons\pbm.ico" /Y
COPY "%~dp0Icons\PCX.ico" "%~dp0Ext-Icons\pcx.ico" /Y
COPY "%~dp0Icons\PEF.ico" "%~dp0Ext-Icons\pef.ico" /Y
COPY "%~dp0Icons\PGM.ico" "%~dp0Ext-Icons\pgm.ico" /Y
COPY "%~dp0Icons\PNG.ico" "%~dp0Ext-Icons\png.ico" /Y
COPY "%~dp0Icons\PPM.ico" "%~dp0Ext-Icons\ppm.ico" /Y
COPY "%~dp0Icons\PSD.ico" "%~dp0Ext-Icons\psd.ico" /Y
COPY "%~dp0Icons\PTX.ico" "%~dp0Ext-Icons\ptx.ico" /Y
COPY "%~dp0Icons\PXN.ico" "%~dp0Ext-Icons\pxn.ico" /Y
COPY "%~dp0Icons\QOI.ico" "%~dp0Ext-Icons\qoi.ico" /Y
COPY "%~dp0Icons\R3D.ico" "%~dp0Ext-Icons\r3d.ico" /Y
COPY "%~dp0Icons\RAF.ico" "%~dp0Ext-Icons\raf.ico" /Y
COPY "%~dp0Icons\RAW.ico" "%~dp0Ext-Icons\raw.ico" /Y
COPY "%~dp0Icons\RW2.ico" "%~dp0Ext-Icons\rw2.ico" /Y
COPY "%~dp0Icons\RWL.ico" "%~dp0Ext-Icons\rwl.ico" /Y
COPY "%~dp0Icons\RWZ.ico" "%~dp0Ext-Icons\rwz.ico" /Y
COPY "%~dp0Icons\SR2.ico" "%~dp0Ext-Icons\sr2.ico" /Y
COPY "%~dp0Icons\SRF.ico" "%~dp0Ext-Icons\srf.ico" /Y
COPY "%~dp0Icons\SRW.ico" "%~dp0Ext-Icons\srw.ico" /Y
COPY "%~dp0Icons\SVG.ico" "%~dp0Ext-Icons\svg.ico" /Y
COPY "%~dp0Icons\TGA.ico" "%~dp0Ext-Icons\tga.ico" /Y
COPY "%~dp0Icons\TIF.ico" "%~dp0Ext-Icons\tif.ico" /Y
COPY "%~dp0Icons\TIFF.ico" "%~dp0Ext-Icons\tiff.ico" /Y
COPY "%~dp0Icons\WEBP.ico" "%~dp0Ext-Icons\webp.ico" /Y
COPY "%~dp0Icons\WIC.ico" "%~dp0Ext-Icons\wic.ico" /Y
COPY "%~dp0Icons\WMF.ico" "%~dp0Ext-Icons\wmf.ico" /Y
COPY "%~dp0Icons\WPG.ico" "%~dp0Ext-Icons\wpg.ico" /Y
COPY "%~dp0Icons\X3F.ico" "%~dp0Ext-Icons\x3f.ico" /Y
COPY "%~dp0Icons\XBM.ico" "%~dp0Ext-Icons\xbm.ico" /Y
COPY "%~dp0Icons\XPM.ico" "%~dp0Ext-Icons\xpm.ico" /Y
COPY "%~dp0Ext-Icons" "%LocalAppData%\Programs\ImageGlass\Ext-Icons" /Y
