@ECHO OFF
MD "%~dp0filetypes"
COPY "%~dp0Icons\3fr.ico" "%~dp0filetypes\image.3fr.ico" /Y
COPY "%~dp0Icons\3g2.ico" "%~dp0filetypes\image.3g2.ico" /Y
COPY "%~dp0Icons\3gp.ico" "%~dp0filetypes\image.3gp.ico" /Y
COPY "%~dp0Icons\7z.ico" "%~dp0filetypes\image.7z.ico" /Y
COPY "%~dp0Icons\aai.ico" "%~dp0filetypes\image.aai.ico" /Y
COPY "%~dp0Icons\afm.ico" "%~dp0filetypes\image.afm.ico" /Y
COPY "%~dp0Icons\ai.ico" "%~dp0filetypes\image.ai.ico" /Y
COPY "%~dp0Icons\alb.ico" "%~dp0filetypes\image.alb.ico" /Y
COPY "%~dp0Icons\alias.ico" "%~dp0filetypes\image.alias.ico" /Y
COPY "%~dp0Icons\als.ico" "%~dp0filetypes\image.als.ico" /Y
COPY "%~dp0Icons\amv.ico" "%~dp0filetypes\image.amv.ico" /Y
COPY "%~dp0Icons\ani.ico" "%~dp0filetypes\image.ani.ico" /Y
COPY "%~dp0Icons\apm.ico" "%~dp0filetypes\image.apm.ico" /Y
COPY "%~dp0Icons\apng.ico" "%~dp0filetypes\image.apng.ico" /Y
COPY "%~dp0Icons\ari.ico" "%~dp0filetypes\image.ari.ico" /Y
COPY "%~dp0Icons\arq.ico" "%~dp0filetypes\image.arq.ico" /Y
COPY "%~dp0Icons\art.ico" "%~dp0filetypes\image.art.ico" /Y
COPY "%~dp0Icons\arw.ico" "%~dp0filetypes\image.arw.ico" /Y
COPY "%~dp0Icons\asf.ico" "%~dp0filetypes\image.asf.ico" /Y
COPY "%~dp0Icons\avi.ico" "%~dp0filetypes\image.avi.ico" /Y
COPY "%~dp0Icons\avif.ico" "%~dp0filetypes\image.avif.ico" /Y
COPY "%~dp0Icons\avifs.ico" "%~dp0filetypes\image.avifs.ico" /Y
COPY "%~dp0Icons\avs.ico" "%~dp0filetypes\image.avs.ico" /Y
COPY "%~dp0Icons\bay.ico" "%~dp0filetypes\image.bay.ico" /Y
COPY "%~dp0Icons\bie.ico" "%~dp0filetypes\image.bie.ico" /Y
COPY "%~dp0Icons\bm.ico" "%~dp0filetypes\image.bm.ico" /Y
COPY "%~dp0Icons\bmp.ico" "%~dp0filetypes\image.bmp.ico" /Y
COPY "%~dp0Icons\bmq.ico" "%~dp0filetypes\image.bmq.ico" /Y
COPY "%~dp0Icons\bpg.ico" "%~dp0filetypes\image.bpg.ico" /Y
COPY "%~dp0Icons\bw.ico" "%~dp0filetypes\image.bw.ico" /Y
COPY "%~dp0Icons\c4.ico" "%~dp0filetypes\image.c4.ico" /Y
COPY "%~dp0Icons\cal.ico" "%~dp0filetypes\image.cal.ico" /Y
COPY "%~dp0Icons\cals.ico" "%~dp0filetypes\image.cals.ico" /Y
COPY "%~dp0Icons\cap.ico" "%~dp0filetypes\image.cap.ico" /Y
COPY "%~dp0Icons\cb7.ico" "%~dp0filetypes\image.cb7.ico" /Y
COPY "%~dp0Icons\cbr.ico" "%~dp0filetypes\image.cbr.ico" /Y
COPY "%~dp0Icons\cbt.ico" "%~dp0filetypes\image.cbt.ico" /Y
COPY "%~dp0Icons\cbz.ico" "%~dp0filetypes\image.cbz.ico" /Y
COPY "%~dp0Icons\cg3.ico" "%~dp0filetypes\image.cg3.ico" /Y
COPY "%~dp0Icons\cg4.ico" "%~dp0filetypes\image.cg4.ico" /Y
COPY "%~dp0Icons\ch.ico" "%~dp0filetypes\image.ch.ico" /Y
COPY "%~dp0Icons\cine.ico" "%~dp0filetypes\image.cine.ico" /Y
COPY "%~dp0Icons\cr2.ico" "%~dp0filetypes\image.cr2.ico" /Y
COPY "%~dp0Icons\cr3.ico" "%~dp0filetypes\image.cr3.ico" /Y
COPY "%~dp0Icons\crr.ico" "%~dp0filetypes\image.crr.ico" /Y
COPY "%~dp0Icons\crw.ico" "%~dp0filetypes\image.crw.ico" /Y
COPY "%~dp0Icons\cs1.ico" "%~dp0filetypes\image.cs1.ico" /Y
COPY "%~dp0Icons\ct.ico" "%~dp0filetypes\image.ct.ico" /Y
COPY "%~dp0Icons\ct1.ico" "%~dp0filetypes\image.ct1.ico" /Y
COPY "%~dp0Icons\ct2.ico" "%~dp0filetypes\image.ct2.ico" /Y
COPY "%~dp0Icons\ct3.ico" "%~dp0filetypes\image.ct3.ico" /Y
COPY "%~dp0Icons\ct4.ico" "%~dp0filetypes\image.ct4.ico" /Y
COPY "%~dp0Icons\cube.ico" "%~dp0filetypes\image.cube.ico" /Y
COPY "%~dp0Icons\cur.ico" "%~dp0filetypes\image.cur.ico" /Y
COPY "%~dp0Icons\cut.ico" "%~dp0filetypes\image.cut.ico" /Y
COPY "%~dp0Icons\dc2.ico" "%~dp0filetypes\image.dc2.ico" /Y
COPY "%~dp0Icons\dcm.ico" "%~dp0filetypes\image.dcm.ico" /Y
COPY "%~dp0Icons\dcr.ico" "%~dp0filetypes\image.dcr.ico" /Y
COPY "%~dp0Icons\dcs.ico" "%~dp0filetypes\image.dcs.ico" /Y
COPY "%~dp0Icons\dcx.ico" "%~dp0filetypes\image.dcx.ico" /Y
COPY "%~dp0Icons\dds.ico" "%~dp0filetypes\image.dds.ico" /Y
COPY "%~dp0Icons\dfont.ico" "%~dp0filetypes\image.dfont.ico" /Y
COPY "%~dp0Icons\dib.ico" "%~dp0filetypes\image.dib.ico" /Y
COPY "%~dp0Icons\dic.ico" "%~dp0filetypes\image.dic.ico" /Y
COPY "%~dp0Icons\djv.ico" "%~dp0filetypes\image.djv.ico" /Y
COPY "%~dp0Icons\djvu.ico" "%~dp0filetypes\image.djvu.ico" /Y
COPY "%~dp0Icons\dng.ico" "%~dp0filetypes\image.dng.ico" /Y
COPY "%~dp0Icons\dpx.ico" "%~dp0filetypes\image.dpx.ico" /Y
COPY "%~dp0Icons\drf.ico" "%~dp0filetypes\image.drf.ico" /Y
COPY "%~dp0Icons\dxo.ico" "%~dp0filetypes\image.dxo.ico" /Y
COPY "%~dp0Icons\eip.ico" "%~dp0filetypes\image.eip.ico" /Y
COPY "%~dp0Icons\epi.ico" "%~dp0filetypes\image.epi.ico" /Y
COPY "%~dp0Icons\eps.ico" "%~dp0filetypes\image.eps.ico" /Y
COPY "%~dp0Icons\epsf.ico" "%~dp0filetypes\image.epsf.ico" /Y
COPY "%~dp0Icons\epsi.ico" "%~dp0filetypes\image.epsi.ico" /Y
COPY "%~dp0Icons\ept.ico" "%~dp0filetypes\image.ept.ico" /Y
COPY "%~dp0Icons\erf.ico" "%~dp0filetypes\image.erf.ico" /Y
COPY "%~dp0Icons\exr.ico" "%~dp0filetypes\image.exr.ico" /Y
COPY "%~dp0Icons\f4v.ico" "%~dp0filetypes\image.f4v.ico" /Y
COPY "%~dp0Icons\ff.ico" "%~dp0filetypes\image.ff.ico" /Y
COPY "%~dp0Icons\fff.ico" "%~dp0filetypes\image.fff.ico" /Y
COPY "%~dp0Icons\fit.ico" "%~dp0filetypes\image.fit.ico" /Y
COPY "%~dp0Icons\fits.ico" "%~dp0filetypes\image.fits.ico" /Y
COPY "%~dp0Icons\fl32.ico" "%~dp0filetypes\image.fl32.ico" /Y
COPY "%~dp0Icons\flv.ico" "%~dp0filetypes\image.flv.ico" /Y
COPY "%~dp0Icons\fts.ico" "%~dp0filetypes\image.fts.ico" /Y
COPY "%~dp0Icons\ftx.ico" "%~dp0filetypes\image.ftx.ico" /Y
COPY "%~dp0Icons\g3.ico" "%~dp0filetypes\image.g3.ico" /Y
COPY "%~dp0Icons\g4.ico" "%~dp0filetypes\image.g4.ico" /Y
COPY "%~dp0Icons\gg.ico" "%~dp0filetypes\image.gg.ico" /Y
COPY "%~dp0Icons\gif.ico" "%~dp0filetypes\image.gif.ico" /Y
COPY "%~dp0Icons\gig.ico" "%~dp0filetypes\image.gig.ico" /Y
COPY "%~dp0Icons\gpr.ico" "%~dp0filetypes\image.gpr.ico" /Y
COPY "%~dp0Icons\hdp.ico" "%~dp0filetypes\image.hdp.ico" /Y
COPY "%~dp0Icons\hdr.ico" "%~dp0filetypes\image.hdr.ico" /Y
COPY "%~dp0Icons\heic.ico" "%~dp0filetypes\image.heic.ico" /Y
COPY "%~dp0Icons\heif.ico" "%~dp0filetypes\image.heif.ico" /Y
COPY "%~dp0Icons\hrz.ico" "%~dp0filetypes\image.hrz.ico" /Y
COPY "%~dp0Icons\icb.ico" "%~dp0filetypes\image.icb.ico" /Y
COPY "%~dp0Icons\icns.ico" "%~dp0filetypes\image.icns.ico" /Y
COPY "%~dp0Icons\ico.ico" "%~dp0filetypes\image.ico.ico" /Y
COPY "%~dp0Icons\iff.ico" "%~dp0filetypes\image.iff.ico" /Y
COPY "%~dp0Icons\iiq.ico" "%~dp0filetypes\image.iiq.ico" /Y
COPY "%~dp0Icons\im1.ico" "%~dp0filetypes\image.im1.ico" /Y
COPY "%~dp0Icons\im24.ico" "%~dp0filetypes\image.im24.ico" /Y
COPY "%~dp0Icons\im32.ico" "%~dp0filetypes\image.im32.ico" /Y
COPY "%~dp0Icons\im8.ico" "%~dp0filetypes\image.im8.ico" /Y
COPY "%~dp0Icons\img.ico" "%~dp0filetypes\image.img.ico" /Y
COPY "%~dp0Icons\inf.ico" "%~dp0filetypes\image.inf.ico" /Y
COPY "%~dp0Icons\j2k.ico" "%~dp0filetypes\image.j2k.ico" /Y
COPY "%~dp0Icons\jbg.ico" "%~dp0filetypes\image.jbg.ico" /Y
COPY "%~dp0Icons\jbig.ico" "%~dp0filetypes\image.jbig.ico" /Y
COPY "%~dp0Icons\jfif.ico" "%~dp0filetypes\image.jfif.ico" /Y
COPY "%~dp0Icons\jif.ico" "%~dp0filetypes\image.jif.ico" /Y
COPY "%~dp0Icons\jng.ico" "%~dp0filetypes\image.jng.ico" /Y
COPY "%~dp0Icons\jp2.ico" "%~dp0filetypes\image.jp2.ico" /Y
COPY "%~dp0Icons\jpc.ico" "%~dp0filetypes\image.jpc.ico" /Y
COPY "%~dp0Icons\jpe.ico" "%~dp0filetypes\image.jpe.ico" /Y
COPY "%~dp0Icons\jpeg.ico" "%~dp0filetypes\image.jpeg.ico" /Y
COPY "%~dp0Icons\jpeg2000.ico" "%~dp0filetypes\image.jpeg2000.ico" /Y
COPY "%~dp0Icons\jpg.ico" "%~dp0filetypes\image.jpg.ico" /Y
COPY "%~dp0Icons\jpx.ico" "%~dp0filetypes\image.jpx.ico" /Y
COPY "%~dp0Icons\jxl.ico" "%~dp0filetypes\image.jxl.ico" /Y
COPY "%~dp0Icons\jxr.ico" "%~dp0filetypes\image.jxr.ico" /Y
COPY "%~dp0Icons\k25.ico" "%~dp0filetypes\image.k25.ico" /Y
COPY "%~dp0Icons\kc2.ico" "%~dp0filetypes\image.kc2.ico" /Y
COPY "%~dp0Icons\kdc.ico" "%~dp0filetypes\image.kdc.ico" /Y
COPY "%~dp0Icons\kla.ico" "%~dp0filetypes\image.kla.ico" /Y
COPY "%~dp0Icons\koa.ico" "%~dp0filetypes\image.koa.ico" /Y
COPY "%~dp0Icons\kra.ico" "%~dp0filetypes\image.kra.ico" /Y
COPY "%~dp0Icons\lbm.ico" "%~dp0filetypes\image.lbm.ico" /Y
COPY "%~dp0Icons\liq.ico" "%~dp0filetypes\image.liq.ico" /Y
COPY "%~dp0Icons\m2ts.ico" "%~dp0filetypes\image.m2ts.ico" /Y
COPY "%~dp0Icons\m2v.ico" "%~dp0filetypes\image.m2v.ico" /Y
COPY "%~dp0Icons\m4v.ico" "%~dp0filetypes\image.m4v.ico" /Y
COPY "%~dp0Icons\mat.ico" "%~dp0filetypes\image.mat.ico" /Y
COPY "%~dp0Icons\mbfavs.ico" "%~dp0filetypes\image.mbfavs.ico" /Y
COPY "%~dp0Icons\mdc.ico" "%~dp0filetypes\image.mdc.ico" /Y
COPY "%~dp0Icons\mef.ico" "%~dp0filetypes\image.mef.ico" /Y
COPY "%~dp0Icons\mfw.ico" "%~dp0filetypes\image.mfw.ico" /Y
COPY "%~dp0Icons\mif.ico" "%~dp0filetypes\image.mif.ico" /Y
COPY "%~dp0Icons\miff.ico" "%~dp0filetypes\image.miff.ico" /Y
COPY "%~dp0Icons\mj2.ico" "%~dp0filetypes\image.mj2.ico" /Y
COPY "%~dp0Icons\mkv.ico" "%~dp0filetypes\image.mkv.ico" /Y
COPY "%~dp0Icons\mng.ico" "%~dp0filetypes\image.mng.ico" /Y
COPY "%~dp0Icons\mos.ico" "%~dp0filetypes\image.mos.ico" /Y
COPY "%~dp0Icons\mov.ico" "%~dp0filetypes\image.mov.ico" /Y
COPY "%~dp0Icons\mp2.ico" "%~dp0filetypes\image.mp2.ico" /Y
COPY "%~dp0Icons\mp4.ico" "%~dp0filetypes\image.mp4.ico" /Y
COPY "%~dp0Icons\mpc.ico" "%~dp0filetypes\image.mpc.ico" /Y
COPY "%~dp0Icons\mpe.ico" "%~dp0filetypes\image.mpe.ico" /Y
COPY "%~dp0Icons\mpeg.ico" "%~dp0filetypes\image.mpeg.ico" /Y
COPY "%~dp0Icons\mpg.ico" "%~dp0filetypes\image.mpg.ico" /Y
COPY "%~dp0Icons\mpv.ico" "%~dp0filetypes\image.mpv.ico" /Y
COPY "%~dp0Icons\mrw.ico" "%~dp0filetypes\image.mrw.ico" /Y
COPY "%~dp0Icons\mts.ico" "%~dp0filetypes\image.mts.ico" /Y
COPY "%~dp0Icons\mtv.ico" "%~dp0filetypes\image.mtv.ico" /Y
COPY "%~dp0Icons\mvg.ico" "%~dp0filetypes\image.mvg.ico" /Y
COPY "%~dp0Icons\mxf.ico" "%~dp0filetypes\image.mxf.ico" /Y
COPY "%~dp0Icons\nef.ico" "%~dp0filetypes\image.nef.ico" /Y
COPY "%~dp0Icons\nif.ico" "%~dp0filetypes\image.nif.ico" /Y
COPY "%~dp0Icons\nrw.ico" "%~dp0filetypes\image.nrw.ico" /Y
COPY "%~dp0Icons\obm.ico" "%~dp0filetypes\image.obm.ico" /Y
COPY "%~dp0Icons\ofm.ico" "%~dp0filetypes\image.ofm.ico" /Y
COPY "%~dp0Icons\ogg.ico" "%~dp0filetypes\image.ogg.ico" /Y
COPY "%~dp0Icons\ogv.ico" "%~dp0filetypes\image.ogv.ico" /Y
COPY "%~dp0Icons\ora.ico" "%~dp0filetypes\image.ora.ico" /Y
COPY "%~dp0Icons\orf.ico" "%~dp0filetypes\image.orf.ico" /Y
COPY "%~dp0Icons\ori.ico" "%~dp0filetypes\image.ori.ico" /Y
COPY "%~dp0Icons\otb.ico" "%~dp0filetypes\image.otb.ico" /Y
COPY "%~dp0Icons\otc.ico" "%~dp0filetypes\image.otc.ico" /Y
COPY "%~dp0Icons\otf.ico" "%~dp0filetypes\image.otf.ico" /Y
COPY "%~dp0Icons\p7.ico" "%~dp0filetypes\image.p7.ico" /Y
COPY "%~dp0Icons\pal.ico" "%~dp0filetypes\image.pal.ico" /Y
COPY "%~dp0Icons\palm.ico" "%~dp0filetypes\image.palm.ico" /Y
COPY "%~dp0Icons\pam.ico" "%~dp0filetypes\image.pam.ico" /Y
COPY "%~dp0Icons\pbm.ico" "%~dp0filetypes\image.pbm.ico" /Y
COPY "%~dp0Icons\pcd.ico" "%~dp0filetypes\image.pcd.ico" /Y
COPY "%~dp0Icons\pcds.ico" "%~dp0filetypes\image.pcds.ico" /Y
COPY "%~dp0Icons\pct.ico" "%~dp0filetypes\image.pct.ico" /Y
COPY "%~dp0Icons\pcx.ico" "%~dp0filetypes\image.pcx.ico" /Y
COPY "%~dp0Icons\pdb.ico" "%~dp0filetypes\image.pdb.ico" /Y
COPY "%~dp0Icons\pdd.ico" "%~dp0filetypes\image.pdd.ico" /Y
COPY "%~dp0Icons\pdf.ico" "%~dp0filetypes\image.pdf.ico" /Y
COPY "%~dp0Icons\pef.ico" "%~dp0filetypes\image.pef.ico" /Y
COPY "%~dp0Icons\pes.ico" "%~dp0filetypes\image.pes.ico" /Y
COPY "%~dp0Icons\pfa.ico" "%~dp0filetypes\image.pfa.ico" /Y
COPY "%~dp0Icons\pfb.ico" "%~dp0filetypes\image.pfb.ico" /Y
COPY "%~dp0Icons\pfm.ico" "%~dp0filetypes\image.pfm.ico" /Y
COPY "%~dp0Icons\pgm.ico" "%~dp0filetypes\image.pgm.ico" /Y
COPY "%~dp0Icons\pgx.ico" "%~dp0filetypes\image.pgx.ico" /Y
COPY "%~dp0Icons\phm.ico" "%~dp0filetypes\image.phm.ico" /Y
COPY "%~dp0Icons\pic.ico" "%~dp0filetypes\image.pic.ico" /Y
COPY "%~dp0Icons\picon.ico" "%~dp0filetypes\image.picon.ico" /Y
COPY "%~dp0Icons\pict.ico" "%~dp0filetypes\image.pict.ico" /Y
COPY "%~dp0Icons\pix.ico" "%~dp0filetypes\image.pix.ico" /Y
COPY "%~dp0Icons\pm.ico" "%~dp0filetypes\image.pm.ico" /Y
COPY "%~dp0Icons\png.ico" "%~dp0filetypes\image.png.ico" /Y
COPY "%~dp0Icons\pnm.ico" "%~dp0filetypes\image.pnm.ico" /Y
COPY "%~dp0Icons\ppm.ico" "%~dp0filetypes\image.ppm.ico" /Y
COPY "%~dp0Icons\ps.ico" "%~dp0filetypes\image.ps.ico" /Y
COPY "%~dp0Icons\ps2.ico" "%~dp0filetypes\image.ps2.ico" /Y
COPY "%~dp0Icons\ps3.ico" "%~dp0filetypes\image.ps3.ico" /Y
COPY "%~dp0Icons\psb.ico" "%~dp0filetypes\image.psb.ico" /Y
COPY "%~dp0Icons\psd.ico" "%~dp0filetypes\image.psd.ico" /Y
COPY "%~dp0Icons\psdt.ico" "%~dp0filetypes\image.psdt.ico" /Y
COPY "%~dp0Icons\ptif.ico" "%~dp0filetypes\image.ptif.ico" /Y
COPY "%~dp0Icons\ptiff.ico" "%~dp0filetypes\image.ptiff.ico" /Y
COPY "%~dp0Icons\ptx.ico" "%~dp0filetypes\image.ptx.ico" /Y
COPY "%~dp0Icons\pwm.ico" "%~dp0filetypes\image.pwm.ico" /Y
COPY "%~dp0Icons\pwp.ico" "%~dp0filetypes\image.pwp.ico" /Y
COPY "%~dp0Icons\pxn.ico" "%~dp0filetypes\image.pxn.ico" /Y
COPY "%~dp0Icons\pxr.ico" "%~dp0filetypes\image.pxr.ico" /Y
COPY "%~dp0Icons\qoi.ico" "%~dp0filetypes\image.qoi.ico" /Y
COPY "%~dp0Icons\qt.ico" "%~dp0filetypes\image.qt.ico" /Y
COPY "%~dp0Icons\qtk.ico" "%~dp0filetypes\image.qtk.ico" /Y
COPY "%~dp0Icons\r3d.ico" "%~dp0filetypes\image.r3d.ico" /Y
COPY "%~dp0Icons\rad.ico" "%~dp0filetypes\image.rad.ico" /Y
COPY "%~dp0Icons\raf.ico" "%~dp0filetypes\image.raf.ico" /Y
COPY "%~dp0Icons\rar.ico" "%~dp0filetypes\image.rar.ico" /Y
COPY "%~dp0Icons\ras.ico" "%~dp0filetypes\image.ras.ico" /Y
COPY "%~dp0Icons\rast.ico" "%~dp0filetypes\image.rast.ico" /Y
COPY "%~dp0Icons\raw.ico" "%~dp0filetypes\image.raw.ico" /Y
COPY "%~dp0Icons\rdc.ico" "%~dp0filetypes\image.rdc.ico" /Y
COPY "%~dp0Icons\rgb.ico" "%~dp0filetypes\image.rgb.ico" /Y
COPY "%~dp0Icons\rgba.ico" "%~dp0filetypes\image.rgba.ico" /Y
COPY "%~dp0Icons\rgbe.ico" "%~dp0filetypes\image.rgbe.ico" /Y
COPY "%~dp0Icons\rgf.ico" "%~dp0filetypes\image.rgf.ico" /Y
COPY "%~dp0Icons\rla.ico" "%~dp0filetypes\image.rla.ico" /Y
COPY "%~dp0Icons\rle.ico" "%~dp0filetypes\image.rle.ico" /Y
COPY "%~dp0Icons\rm.ico" "%~dp0filetypes\image.rm.ico" /Y
COPY "%~dp0Icons\rs.ico" "%~dp0filetypes\image.rs.ico" /Y
COPY "%~dp0Icons\rw2.ico" "%~dp0filetypes\image.rw2.ico" /Y
COPY "%~dp0Icons\rwl.ico" "%~dp0filetypes\image.rwl.ico" /Y
COPY "%~dp0Icons\rwz.ico" "%~dp0filetypes\image.rwz.ico" /Y
COPY "%~dp0Icons\sai.ico" "%~dp0filetypes\image.sai.ico" /Y
COPY "%~dp0Icons\scr.ico" "%~dp0filetypes\image.scr.ico" /Y
COPY "%~dp0Icons\sct.ico" "%~dp0filetypes\image.sct.ico" /Y
COPY "%~dp0Icons\sfw.ico" "%~dp0filetypes\image.sfw.ico" /Y
COPY "%~dp0Icons\sgi.ico" "%~dp0filetypes\image.sgi.ico" /Y
COPY "%~dp0Icons\sixel.ico" "%~dp0filetypes\image.sixel.ico" /Y
COPY "%~dp0Icons\sr.ico" "%~dp0filetypes\image.sr.ico" /Y
COPY "%~dp0Icons\sr2.ico" "%~dp0filetypes\image.sr2.ico" /Y
COPY "%~dp0Icons\srf.ico" "%~dp0filetypes\image.srf.ico" /Y
COPY "%~dp0Icons\srw.ico" "%~dp0filetypes\image.srw.ico" /Y
COPY "%~dp0Icons\sti.ico" "%~dp0filetypes\image.sti.ico" /Y
COPY "%~dp0Icons\sun.ico" "%~dp0filetypes\image.sun.ico" /Y
COPY "%~dp0Icons\svg.ico" "%~dp0filetypes\image.svg.ico" /Y
COPY "%~dp0Icons\svgz.ico" "%~dp0filetypes\image.svgz.ico" /Y
COPY i%~dp0Icons\co" "tarfiletypes\.bz2.ico" "%~dp0image.tar.bz2 /Y
COPY i%~dp0Icons\co" "tarfiletypes\.gz.ico" "%~dp0image.tar.gz /Y
COPY "%~dp0Icons\tar.ico" "%~dp0filetypes\image.tar.ico" /Y
COPY i%~dp0Icons\co" "tarfiletypes\.lz.ico" "%~dp0image.tar.lz /Y
COPY i%~dp0Icons\co" "tarfiletypes\.lzma.ico" "%~dp0image.tar.lzma /Y
COPY i%~dp0Icons\co" "tarfiletypes\.lzo.ico" "%~dp0image.tar.lzo /Y
COPY i%~dp0Icons\co" "tarfiletypes\.xz.ico" "%~dp0image.tar.xz /Y
COPY i%~dp0Icons\co" "tarfiletypes\.zst.ico" "%~dp0image.tar.zst /Y
COPY "%~dp0Icons\taz.ico" "%~dp0filetypes\image.taz.ico" /Y
COPY "%~dp0Icons\tb2.ico" "%~dp0filetypes\image.tb2.ico" /Y
COPY "%~dp0Icons\tbz.ico" "%~dp0filetypes\image.tbz.ico" /Y
COPY "%~dp0Icons\tbz2.ico" "%~dp0filetypes\image.tbz2.ico" /Y
COPY "%~dp0Icons\tga.ico" "%~dp0filetypes\image.tga.ico" /Y
COPY "%~dp0Icons\tgz.ico" "%~dp0filetypes\image.tgz.ico" /Y
COPY "%~dp0Icons\tif.ico" "%~dp0filetypes\image.tif.ico" /Y
COPY "%~dp0Icons\tiff.ico" "%~dp0filetypes\image.tiff.ico" /Y
COPY "%~dp0Icons\tim.ico" "%~dp0filetypes\image.tim.ico" /Y
COPY "%~dp0Icons\tlz.ico" "%~dp0filetypes\image.tlz.ico" /Y
COPY "%~dp0Icons\ts.ico" "%~dp0filetypes\image.ts.ico" /Y
COPY "%~dp0Icons\ttc.ico" "%~dp0filetypes\image.ttc.ico" /Y
COPY "%~dp0Icons\ttf.ico" "%~dp0filetypes\image.ttf.ico" /Y
COPY "%~dp0Icons\txz.ico" "%~dp0filetypes\image.txz.ico" /Y
COPY "%~dp0Icons\tZ.ico" "%~dp0filetypes\image.tZ.ico" /Y
COPY "%~dp0Icons\tz2.ico" "%~dp0filetypes\image.tz2.ico" /Y
COPY "%~dp0Icons\tzst.ico" "%~dp0filetypes\image.tzst.ico" /Y
COPY "%~dp0Icons\unknown.ico" "%~dp0filetypes\image.unknown.ico" /Y
COPY "%~dp0Icons\vda.ico" "%~dp0filetypes\image.vda.ico" /Y
COPY "%~dp0Icons\vic.ico" "%~dp0filetypes\image.vic.ico" /Y
COPY "%~dp0Icons\vicar.ico" "%~dp0filetypes\image.vicar.ico" /Y
COPY "%~dp0Icons\viff.ico" "%~dp0filetypes\image.viff.ico" /Y
COPY "%~dp0Icons\vob.ico" "%~dp0filetypes\image.vob.ico" /Y
COPY "%~dp0Icons\vst.ico" "%~dp0filetypes\image.vst.ico" /Y
COPY "%~dp0Icons\vtf.ico" "%~dp0filetypes\image.vtf.ico" /Y
COPY "%~dp0Icons\wbmp.ico" "%~dp0filetypes\image.wbmp.ico" /Y
COPY "%~dp0Icons\wdp.ico" "%~dp0filetypes\image.wdp.ico" /Y
COPY "%~dp0Icons\webm.ico" "%~dp0filetypes\image.webm.ico" /Y
COPY "%~dp0Icons\webp.ico" "%~dp0filetypes\image.webp.ico" /Y
COPY "%~dp0Icons\wmf.ico" "%~dp0filetypes\image.wmf.ico" /Y
COPY "%~dp0Icons\wmv.ico" "%~dp0filetypes\image.wmv.ico" /Y
COPY "%~dp0Icons\wmz.ico" "%~dp0filetypes\image.wmz.ico" /Y
COPY "%~dp0Icons\wpg.ico" "%~dp0filetypes\image.wpg.ico" /Y
COPY "%~dp0Icons\x.ico" "%~dp0filetypes\image.x.ico" /Y
COPY "%~dp0Icons\x3f.ico" "%~dp0filetypes\image.x3f.ico" /Y
COPY "%~dp0Icons\xbm.ico" "%~dp0filetypes\image.xbm.ico" /Y
COPY "%~dp0Icons\xcf.ico" "%~dp0filetypes\image.xcf.ico" /Y
COPY "%~dp0Icons\xpm.ico" "%~dp0filetypes\image.xpm.ico" /Y
COPY "%~dp0Icons\xv.ico" "%~dp0filetypes\image.xv.ico" /Y
COPY "%~dp0Icons\xwd.ico" "%~dp0filetypes\image.xwd.ico" /Y
COPY "%~dp0Icons\zip.ico" "%~dp0filetypes\image.zip.ico" /Y
COPY "%~dp0filetypes" "%ProgramFiles%\PhotoQt\filetypes" /Y
